[package]
name = "Solana-Rust-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-client = "3.1.8"
solana-sdk = "3.0.0" 
solana-system-interface = {version = "3.0.0", features=["bincode"]}
tokio = "1.49.0"
anyhow = "1.0"